version: '3.1'
services:
  main:
    build: ./
    container_name: telros-test
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/telros-test
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  db:
    image: postgres:15-alpine
    container_name: telros-test-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=telros-test
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
